### ISSUE TITLE
pingExec() always returns 0ms under Windows

### ISSUE THREAD

**Issue by networkfudge** [geerlingguy/Ping#25]
`$time_param` appears to be set correctly under the `if` statement for Windows file systems but the resulting `$output` array retains the keys after filtering out the empty lines (the very first line being empty is what is actually causing the problem).

Can be fixed by changing line `192` in `Ping.php` from:
> $output = array_filter($output);

to

> $output = array_values(array_filter($output));

**Comment by geerlingguy** [comment]
Thanks for the suggestion! It looks like PR #20 should fix this by doing a very similar thing.

**Comment by geerlingguy** [comment]
Should be fixed in PR #20.
