### ISSUE TITLE
Issues with autoload

### ISSUE THREAD

**Issue by joemsanchez** [geerlingguy/Ping#34]
I love everything about your application.  It was exactly what I was looking for!  I integrated it into an internal app I built for my job.  I developed it on my laptop running xampp, worked perfectly.  I wanted to start using it internally, so I moved it to a ubuntu box.  Among other issues that popped up, I haven't been able to get this to work.  The error I get is "Fatal error: Class 'PHPUnit_Framework_TestCase' not found in ..." I googled this, and haven't found much in the way of a fix.  Any suggestions?

**Comment by joemsanchez** [comment]
So I'll answer my question here, and for those who want to ask the same question before coffee.  Need install PHPunit framework you newb!

**Comment by geerlingguy** [comment]
@joemsanchez - Thanks for posting the answer! Though, unless you want to run the unit tests (in https://github.com/geerlingguy/Ping/blob/1.x/JJG/PingTest.php), you shouldn't need PHPunit installed. If you install the library via Composer (e.g. `composer require geerlingguy/Ping:1.*`), Composer will download any required dependencies automatically :)
