### ISSUE TITLE
Ping fails inside cron

### ISSUE THREAD

**Issue by ProfM2** [geerlingguy/Ping#46]
I have Ping setup inside of a command-line script that, when run on the command-line, everything works great.  I get valid data.

However, when I place the exact same command inside of a crontab, Ping returns with a 'false', however the rest of the script works perfectly, so I know that everything is running fine.

I'm using the exec() style of calling.  Is there a better method to get valid data from within a cron job?

**Comment by Mjuk-Biltvatt** [comment]
@ProfM2 did you ever find a solution?

**Comment by ProfM2** [comment]
Unfortunately no.  I ended up removing the ping check for the cron process.

**Comment by ProfM2** [comment]
Well, I needed this feature to work, so after a bit of testing, discovered in my crontab file, /bin was not in the path.  After adding that, ping works great.

**Comment by geerlingguy** [comment]
Thanks for posting your solution! Just noting that 99% of the time when I have an issue that comes up during cron runs but not when run as the regular user, it comes down to the `$PATH` or some other env variable being different.
