### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by Sohib** [geerlingguy/Ping#47]
I think ipv6 should be supported in this package, probably switching to using `ping6` if host name URL has `:` what do you think?

**Comment by geerlingguy** [comment]
That would be a good idea. I only use this on a couple smaller sites where I don't (yet) need to support IPv6 though, so it's not a priority for me (yet).

**Comment by lubber-de** [comment]
@Sohib What does not work for you?

All of this works fine for me already:
```php
$ping = new Ping('::1');
$ping = new Ping('0:0:0:0:0:ffff:7f00:1');
```

**Comment by Sohib** [comment]
@lubber-de have you tried to execute `$ping->ping()` it returns `false` in case of using ipv6.

**Comment by lubber-de** [comment]
@Sohib Yes, it works for me returning the latency as expected... That's why I was asking

**Comment by Sohib** [comment]
@lubber-de Well .. my ISP doesn't support ipv6 so I can't verify now, but I noticed that the developer is using `ping` for ipv4 and ipv6, but I thought  `ping6` or `ping -6` are more appropriate for ipv6 .
