### ISSUE TITLE
Ping status is always false when system language is Chinese

### ISSUE THREAD

**Issue by ghost** [geerlingguy/Ping#49]
May be the cause of garbled? My system language is Chinese.

![Snipaste_02](https://user-images.githubusercontent.com/21291399/63161043-bd295f80-c051-11e9-8914-c33ed483aaca.jpg)

![Snipaste_08](https://user-images.githubusercontent.com/21291399/63160662-e1d10780-c050-11e9-8a47-5e36c7dcd034.jpg)

**Comment by geerlingguy** [comment]
@liuxu379 - Unfortunately my experience dealing with most other language is minimal, and I'm guessing the parsing that the Ping library is using is not working with the Chinese output.

It's trying to find the word 'time' but not finding it.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/Ping/issues/5

Moving discussion to that issue.

**Comment by ghost** [comment]
I deleted the "time" checksum and it works fine, thank you.

`$response = preg_match("/time(?:=|<)(?<time>[\.0-9]+)(?:|\s)ms/", $output[1], $matches);`

`$response = preg_match("/(?<time>[\.0-9]+)(?:|\s)ms/", $output[1], $matches);`
