### ISSUE TITLE
host not found

### ISSUE THREAD

**Issue by gragia79** [geerlingguy/Ping#51]
I use version 1.x
I use the following code:
```
$host = "localhost" or "127.0.0.1"
no change result...
$ping = new Ping($host);
        $ping->setTtl(128);
        $ping->setTimeout(5);
        $latency = $ping->ping();
        if ($latency !== false) {
            return $latency; 
        }else{
            return "No Host";
        }
```

but cannot find the host.

**Comment by villejus** [comment]
I have the same issue trying via my test script via Apache. However, same test php-script via command line works.. This is an SELinux issue, which I am not sure how to avoid other than disabling SELinux until time being.

**Comment by iandk** [comment]
Same issue, CLI works, Web does not

**Comment by Luxian** [comment]
I would say it's most probably a limitation of the web server. When calling `$ping->ping()` with no arguments, you are using the `exec` method (which might be very limited).

Try the other methods: `$ping->ping('fsockopen')`, `$ping->ping('socket')`.

**Comment by arafatx** [comment]
> I have the same issue trying via my test script via Apache. However, same test php-script via command line works.. This is an SELinux issue, which I am not sure how to avoid other than disabling SELinux until time being.

my SELinux is disabled. Not an issue here.

> I would say it's most probably a limitation of the web server. When calling `$ping->ping()` with no arguments, you are using the `exec` method (which might be very limited).
> 
> Try the other methods: `$ping->ping('fsockopen')`, `$ping->ping('socket')`.

this doesn't validate fake domain which should return "No host".
