### ISSUE TITLE
Possible to fake/mock?

### ISSUE THREAD

**Issue by nexxai** [geerlingguy/Ping#55]
I need to unit test a method that uses this package but I can't figure out how to fake out the request since my CI/CD infrastructure blocks outbound ICMP.  Are you able to either A) add the ability to fake the request by adding a static method like Ping::fake(['success' => true]) / Ping::fake(['success' => false]) before the actual Ping::get(), or B) explain how I could use something like Mockery to do this?

**Comment by geerlingguy** [comment]
That's a good question. I would be willing to merge a change to add a `fake` function for mocking purposes.

Alternatively, could you at least ping localhost (`127.0.0.1`) for a success test, and any external IP for a fail if it's all blocked outbound?
