### ISSUE TITLE
why only integer timeout ?

### ISSUE THREAD

**Issue by djdance** [geerlingguy/Ping#65]
Hi! I need shorter timeout (0.5), but enable to set it, because it is integer in code.
And, what is more dangerous, setting timeout to 0.5 will hang a request (if host is dead).
So please, 
1. could you make it float? for linux
2. add a note to start page example, about "don't set float timeout, it will be treated as no timeout"
thanks

**Comment by geerlingguy** [comment]
I would consider making a change to allow a float; as you say it is a bit risky and also sometimes unsupported.
